FROM node:20.10.0-alpine

# set working directory
WORKDIR /app/ToDoWeb
EXPOSE 4201

# add `/app/node_modules/.bin` to $PATH
ENV PATH /app/ToDoWeb/node_modules/.bin:$PATH

# install and cache app dependencies
COPY ./ToDoWeb/package.json /app/ToDoWeb/package.json
RUN npm install
RUN npm install -g @angular/cli@16.2.2

COPY ./ToDoWeb /app/ToDoWeb/

# start app
# CMD ng serve --host 0.0.0.0