version: '3.4'

services:
  todo:
    image: ${DOCKER_REGISTRY-}todo
    build:
      context: .
      dockerfile: ToDo/Dockerfile 
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ASPNETCORE_HTTP_PORTS=8080
      - ASPNETCORE_HTTPS_PORTS=8081
    ports:
      - "8080:8080"
      - "8081:8081" 
    links:
      - "db:database"
    depends_on:
      db:
        condition: service_healthy
        
  db:
    container_name: postgresTodo
    image: postgres:alpine
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: dockerTodo
      POSTGRES_DB: ToDo
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -d ToDo -U postgres"]
      interval: 0s
      timeout: 10s
      retries: 3
  cache:
    container_name: redisToDo
    image: redis:alpine
    ports:
      - "6379:6379"
